// <auto-generated />
namespace ItemsReport_Web1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTheCommon3Tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTheCommon3Tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201708181731173_AddTheCommon3Tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
