// <auto-generated />
namespace ItemsReport_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_EnteredBy_Column_In_NewPrimaryPositions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_EnteredBy_Column_In_NewPrimaryPositions));
        
        string IMigrationMetadata.Id
        {
            get { return "201708041920490_Add_EnteredBy_Column_In_NewPrimaryPositions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
